<?php

namespace AppBundle\Repository;

/**
 * Type_annonceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Type_annonceRepository extends \Doctrine\ORM\EntityRepository
{
    
}
